### ISSUE TITLE
Vim Grand requires changes to build.gradle

### ISSUE THREAD

**Issue by DonnieWest** [meonlol/vim-grand#2]
This can be solved by placing a file in $HOME/.gradle/init.d/grand-init.gradle with the following contents:

```
allprojects {
    apply from: 'https://raw.githubusercontent.com/meonlol/vim-grand/refactor/grand.gradle'
}
```

@meonlol would you be interested in a pull request that would automatically create this file for the user?

**Comment by meonlol** [comment]
Awesome idea. That would solve a annoyance I've had for quite a while.
But how do you suggest implementing this?

**Comment by DonnieWest** [comment]
A simple install.sh that sticks the above script in the appropriate
directory should suffice, or the Vim plugin can check for it and create it
on start.

Just tell me which you prefer and I'll send you a pull request

**Comment by DonnieWest** [comment]
Sorry, originally read the above when tired and replied without fully understanding your concerns. 

It can totally be an option flipped in their vimrc or manually done with the install.sh to put the user in complete control. Also, the grand-init file can refer to a snapshot instead of the master HEAD of Grand.gradle or referenced from the Vim plugin directory instead of downloaded

**Comment by meonlol** [comment]
I've been thinking for quite a while now about what would be the best way to do this. And I've come to the conclusion that I would not like it if some plugin would change system wide settings on my machine. Especially when it is a project related setting that might be cloned on some other machine.
It just feels like a hack that way.

I think I'd rather tell users in the Readme that they have to put this line in their build.gradle to be able to use this functionality, and how they can do it system wide if they want. It's only the one line after all and they'll have to find out that they'll have to call `gradle outputPaths` anyway...
```
apply from: 'https://raw.githubusercontent.com/meonlol/vim-grand/refactor/grand.gradle'
```

I am thankful for the suggestion though. I didn't know you could apply from an url directly and the grand.gradle in the project folder made a really messy installation and update procedure the way it was.
